proxy:
  listen:
    address: "127.0.0.1"
    port: 8080
  services:
    - name: my-service
      domain: my-service.my-company.com
      hosts:
      - address: "127.0.0.1"
        port: 9091
      - address: "127.0.0.1"
        port: 9092